### PR TITLE
Fixes for error parameter

### PR DESCRIPTION
**Pull request by joscha**
Not sure how and why that went through the feature build branch...

references #21

### CODE REVIEW

**Comment by rmanalan** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rGsCYzef&#x2F;6-create-bello-spec"> Create Bello spec</a>

**Comment by megancook** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rGsCYzef&#x2F;6-create-bello-spec"> Create Bello spec</a>

**Comment by joscha** [comment]
Something strange is going on here - it builds completely fine locally.

**Comment by joscha** [comment]
Found it - the `before_script` always checked out the origin `caribou` branch. Added the logic for master into the scripts.

**Comment by joscha** [comment]
cc @jpnelson

**Pull request merged**
