### PR TITLE
refactor(cli): allow cli to accept flags

### PR DESCRIPTION
**Pull request by vovacodes**
affects: lerna-semantic-release

also print --help message with usage documentation

Should help with implementing #67 and #66

### CODE REVIEW

**Review by jpnelson — APPROVED** [review]

**Comment by jpnelson** [comment]
LGTM :) are you planning on adding additional flags to pre / post / perform as well?

**Comment by jpnelson** [comment]
Oh, also, do you want this to do a release? If so, it should probably be a feature commit.

**Comment by vovacodes** [comment]
No I don't think this needs to be released, it should just facilitate the work on the tickets I mentioned. What about the flags, I thought about --dry-run and something for 'post' to allow the append mode for CHANGELOG

**Comment by vovacodes** [comment]
@jpnelson So can we merge this?

**Comment by jpnelson** [comment]
Sorry, I thought I already merged this one. Sure :)

**Pull request merged**
