### PR TITLE
Fix undefined var scopedPublicPackage

### PR DESCRIPTION
**Pull request by singuerinc**

### CODE REVIEW

**Review by jpnelson — APPROVED** [review]

**Comment by jpnelson** [comment]
I'll merge this now since it's clearly broken, but it'd be good to back and write a test that would've caught this.

**Comment by jpnelson** [comment]
I just realised this won't get released without a proper commit message – I'll amend it

**Comment by vovacodes** [comment]
@jpnelson we might add a commit message format validation with a tool like [validate-commit-msg](https://www.npmjs.com/package/validate-commit-msg) to avoid this situations

**Comment by vovacodes** [comment]
@jpnelson 

>  but it'd be good to back and write a test that would've caught this.

In this particular case, even simple linting tool would spot the error, so maybe we should also add eslint to the project? What do you think?

**Comment by jpnelson** [comment]
Both excellent suggestions – I'll make issues for both :)

**Pull request merged**
